name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PureScript
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: latest
          psa: latest
          spago: latest
          purs-tidy: latest

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Check formatting
        run: purs-tidy check src test

      - name: Install dependencies
        run: spago install

      - name: Build
        run: spago build

      - name: Test
        run: spago test --no-install
